-- MySQL Workbench Synchronization
-- Generated: 2015-11-25 16:14
-- Model: OSCampus Database
-- Version: 1.0
-- Project: OSCampus
-- Author: Bill Tomczak

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='';

ALTER TABLE `#__oscampus_tags`
ADD COLUMN `created` DATETIME NULL DEFAULT NULL AFTER `alias`,
ADD COLUMN `created_by` INT(11) NULL DEFAULT NULL AFTER `created`,
ADD COLUMN `created_by_alias` VARCHAR(255) NULL DEFAULT NULL AFTER `created_by`,
ADD COLUMN `modified` DATETIME NULL DEFAULT NULL AFTER `created_by_alias`,
ADD COLUMN `modified_by` INT(11) NULL DEFAULT NULL AFTER `modified`,
ADD COLUMN `checked_out` INT(11) NULL DEFAULT NULL AFTER `modified_by`,
ADD COLUMN `checked_out_time` DATETIME NULL DEFAULT NULL AFTER `checked_out`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
