-- MySQL Script generated by MySQL Workbench
-- 04/22/15 09:46:08
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema OSCampus
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `ext53_oscampus_pathways`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ext53_oscampus_pathways` ;

CREATE TABLE IF NOT EXISTS `ext53_oscampus_pathways` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `users_id` INT NULL COMMENT 'Owner FK of this pathway (optional)',
  `title` VARCHAR(255) NOT NULL COMMENT 'Pathway name',
  `alias` VARCHAR(255) NOT NULL COMMENT 'URL safe pathway name',
  `description` TEXT NOT NULL COMMENT 'Full pathway description',
  `image` VARCHAR(255) NOT NULL COMMENT 'Thumbnail image for pathway',
  `published` INT NOT NULL,
  `ordering` INT NOT NULL,
  `created` DATETIME NULL,
  `created_by` INT NULL,
  `created_by_alias` VARCHAR(255) NULL,
  `modified` DATETIME NULL,
  `modified_by` INT NULL,
  `checked_out` INT NULL,
  `checked_out_time` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = 'Courses of study';


-- -----------------------------------------------------
-- Table `ext53_oscampus_instructors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ext53_oscampus_instructors` ;

CREATE TABLE IF NOT EXISTS `ext53_oscampus_instructors` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `users_id` INT NOT NULL COMMENT 'User FK',
  `image` VARCHAR(255) NOT NULL COMMENT 'Head shot image for instructor',
  `bio` TEXT NOT NULL COMMENT 'Instructor biography',
  `parameters` TEXT NOT NULL COMMENT 'Misc information about instructor',
  `created` DATETIME NULL,
  `created_by` INT NULL,
  `created_by_alias` VARCHAR(255) NULL,
  `modified` DATETIME NULL,
  `modified_by` INT NULL,
  `checked_out` INT NULL,
  `checked_out_time` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idx_users_id` (`users_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ext53_oscampus_courses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ext53_oscampus_courses` ;

CREATE TABLE IF NOT EXISTS `ext53_oscampus_courses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `instructors_id` INT NULL COMMENT 'Instructors FK',
  `difficulty` INT NOT NULL COMMENT 'Difficulty/Level higher = harder',
  `length` INT NOT NULL COMMENT 'Time to take course in minutes',
  `title` VARCHAR(255) NOT NULL COMMENT 'Course name',
  `alias` VARCHAR(255) NOT NULL COMMENT 'URL safe course name',
  `image` VARCHAR(255) NOT NULL COMMENT 'Thumnail image for course',
  `published` INT NOT NULL DEFAULT 1,
  `publish_up` DATETIME NULL,
  `publish_down` DATETIME NULL,
  `created` DATETIME NULL,
  `created_by` INT NOT NULL,
  `created_by_alias` VARCHAR(255) NOT NULL,
  `modified` DATETIME NULL,
  `modified_by` INT NULL,
  `checked_out` INT NULL,
  `checked_out_time` DATETIME NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `courses_instructors`
    FOREIGN KEY (`instructors_id`)
    REFERENCES `ext53_oscampus_instructors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'All Courses of study';


-- -----------------------------------------------------
-- Table `ext53_oscampus_modules`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ext53_oscampus_modules` ;

CREATE TABLE IF NOT EXISTS `ext53_oscampus_modules` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `courses_id` INT NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `alias` VARCHAR(255) NOT NULL,
  `description` TEXT NOT NULL,
  `published` INT NOT NULL,
  `ordering` INT NOT NULL,
  `access` INT NOT NULL,
  `created` DATETIME NULL,
  `created_by` INT NULL,
  `created_by_alias` VARCHAR(255) NULL,
  `modified` DATETIME NULL,
  `modified_by` INT NULL,
  `checked_out` INT NULL,
  `checked_out_time` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `idx_modules_courses` (`courses_id` ASC),
  CONSTRAINT `modules_courses`
    FOREIGN KEY (`courses_id`)
    REFERENCES `ext53_oscampus_courses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ext53_oscampus_lessons`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ext53_oscampus_lessons` ;

CREATE TABLE IF NOT EXISTS `ext53_oscampus_lessons` (
  `id` INT NOT NULL,
  `modules_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `lessons_modules_idx` (`modules_id` ASC),
  CONSTRAINT `lessons_modules`
    FOREIGN KEY (`modules_id`)
    REFERENCES `ext53_oscampus_modules` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ext53_oscampus_certificates`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ext53_oscampus_certificates` ;

CREATE TABLE IF NOT EXISTS `ext53_oscampus_certificates` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `users_id` INT NOT NULL,
  `courses_id` INT NOT NULL,
  `date_earned` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idx_certificates` (`users_id` ASC, `courses_id` ASC),
  INDEX `idx_certificates_courses` (`courses_id` ASC),
  CONSTRAINT `certificates_courses`
    FOREIGN KEY (`courses_id`)
    REFERENCES `ext53_oscampus_courses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ext53_oscampus_courses_pathways`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ext53_oscampus_courses_pathways` ;

CREATE TABLE IF NOT EXISTS `ext53_oscampus_courses_pathways` (
  `courses_id` INT NOT NULL,
  `pathways_id` INT NOT NULL,
  `ordering` INT NOT NULL,
  PRIMARY KEY (`courses_id`, `pathways_id`),
  INDEX `idx_pathways_courses` (`pathways_id` ASC),
  CONSTRAINT `courses_pathways`
    FOREIGN KEY (`courses_id`)
    REFERENCES `ext53_oscampus_courses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `pathways_courses`
    FOREIGN KEY (`pathways_id`)
    REFERENCES `ext53_oscampus_pathways` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ext53_oscampus_users_lessons`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ext53_oscampus_users_lessons` ;

CREATE TABLE IF NOT EXISTS `ext53_oscampus_users_lessons` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `users_id` INT NOT NULL,
  `lessons_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `idx_lessons_users` (`lessons_id` ASC),
  CONSTRAINT `lessons_users`
    FOREIGN KEY (`lessons_id`)
    REFERENCES `ext53_oscampus_lessons` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
