-- MySQL Script generated by MySQL Workbench
-- 04/16/15 16:20:50
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema OSCampus
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `ext53_oscampus_pathways`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ext53_oscampus_pathways` ;

CREATE TABLE IF NOT EXISTS `ext53_oscampus_pathways` (
  `id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ext53_oscampus_instructors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ext53_oscampus_instructors` ;

CREATE TABLE IF NOT EXISTS `ext53_oscampus_instructors` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ext53_oscampus_classes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ext53_oscampus_classes` ;

CREATE TABLE IF NOT EXISTS `ext53_oscampus_classes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `instructors_id` INT NULL,
  `levels_id` INT NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `alias` VARCHAR(255) NOT NULL,
  `image` VARCHAR(255) NOT NULL,
  `published` INT NOT NULL DEFAULT 1,
  `publish_up` DATETIME NULL,
  `publish_down` DATETIME NULL,
  `ordering` INT NOT NULL DEFAULT 0,
  `created` DATETIME NULL,
  `created_by` INT NOT NULL,
  `created_by_alias` VARCHAR(255) NOT NULL,
  `modified` DATETIME NULL,
  `modified_by` INT NULL,
  `checked_out` INT NULL,
  `checked_out_time` DATETIME NULL,
  `metakey` VARCHAR(255) NOT NULL,
  `metadesc` TEXT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `classes_instructors`
    FOREIGN KEY (`instructors_id`)
    REFERENCES `ext53_oscampus_instructors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ext53_oscampus_levels`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ext53_oscampus_levels` ;

CREATE TABLE IF NOT EXISTS `ext53_oscampus_levels` (
  `id` INT NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ext53_oscampus_lessons`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ext53_oscampus_lessons` ;

CREATE TABLE IF NOT EXISTS `ext53_oscampus_lessons` (
  `id` INT NOT NULL,
  `levels_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `idx_lessons_levels` (`levels_id` ASC),
  CONSTRAINT `lessons_levels`
    FOREIGN KEY (`levels_id`)
    REFERENCES `ext53_oscampus_levels` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ext53_oscampus_students`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ext53_oscampus_students` ;

CREATE TABLE IF NOT EXISTS `ext53_oscampus_students` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ext53_oscampus_certificates`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ext53_oscampus_certificates` ;

CREATE TABLE IF NOT EXISTS `ext53_oscampus_certificates` (
  `id` INT NOT NULL,
  `students_id` INT NOT NULL,
  `classes_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idx_certificates` (`students_id` ASC, `classes_id` ASC),
  INDEX `idx_certificates_classes` (`classes_id` ASC),
  CONSTRAINT `certificates_students`
    FOREIGN KEY (`students_id`)
    REFERENCES `ext53_oscampus_students` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `certificates_classes`
    FOREIGN KEY (`classes_id`)
    REFERENCES `ext53_oscampus_classes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ext53_oscampus_classes_pathways`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ext53_oscampus_classes_pathways` ;

CREATE TABLE IF NOT EXISTS `ext53_oscampus_classes_pathways` (
  `classes_id` INT NOT NULL,
  `pathways_id` INT NOT NULL,
  PRIMARY KEY (`classes_id`, `pathways_id`),
  INDEX `idx_pathways_classes` (`pathways_id` ASC),
  CONSTRAINT `classes_pathways`
    FOREIGN KEY (`classes_id`)
    REFERENCES `ext53_oscampus_classes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `pathways_classes`
    FOREIGN KEY (`pathways_id`)
    REFERENCES `ext53_oscampus_pathways` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ext53_oscampus_modules`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ext53_oscampus_modules` ;

CREATE TABLE IF NOT EXISTS `ext53_oscampus_modules` (
  `id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ext53_oscampus_classes_modules`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ext53_oscampus_classes_modules` ;

CREATE TABLE IF NOT EXISTS `ext53_oscampus_classes_modules` (
  `classes_id` INT NOT NULL,
  `modules_id` INT NOT NULL,
  PRIMARY KEY (`classes_id`, `modules_id`),
  INDEX `idx_modules_classes` (`modules_id` ASC),
  CONSTRAINT `classes_modules`
    FOREIGN KEY (`classes_id`)
    REFERENCES `ext53_oscampus_classes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `modules_classes`
    FOREIGN KEY (`modules_id`)
    REFERENCES `ext53_oscampus_modules` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ext53_oscampus_modules_lessons`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ext53_oscampus_modules_lessons` ;

CREATE TABLE IF NOT EXISTS `ext53_oscampus_modules_lessons` (
  `modules_id` INT NOT NULL,
  `lessons_id` INT NOT NULL,
  PRIMARY KEY (`modules_id`, `lessons_id`),
  INDEX `idx_lessons_modules` (`lessons_id` ASC),
  CONSTRAINT `modules_lessons`
    FOREIGN KEY (`modules_id`)
    REFERENCES `ext53_oscampus_modules` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `lessons_modules`
    FOREIGN KEY (`lessons_id`)
    REFERENCES `ext53_oscampus_lessons` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ext53_oscampus_students_lessons`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ext53_oscampus_students_lessons` ;

CREATE TABLE IF NOT EXISTS `ext53_oscampus_students_lessons` (
  `students_id` INT NOT NULL,
  `lessons_id` INT NOT NULL,
  PRIMARY KEY (`students_id`, `lessons_id`),
  INDEX `idx_lessons_students` (`lessons_id` ASC),
  CONSTRAINT `students_lessons`
    FOREIGN KEY (`students_id`)
    REFERENCES `ext53_oscampus_students` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `lessons_students`
    FOREIGN KEY (`lessons_id`)
    REFERENCES `ext53_oscampus_lessons` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `ext53_oscampus_levels`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `ext53_oscampus_levels` (`id`, `title`) VALUES (1, 'Beginner');
INSERT INTO `ext53_oscampus_levels` (`id`, `title`) VALUES (2, 'Intermediate');
INSERT INTO `ext53_oscampus_levels` (`id`, `title`) VALUES (3, 'Advanced');

COMMIT;

